### ISSUE TITLE
Use ChoicesEnum Lib

### ISSUE THREAD

**Issue by rmad17** [reckonsys/opensteer#19]
For `PositiveSmallIntegerField` where we are using for Choices we can use 
https://github.com/loggi/python-choicesenum/ .
Then we can write the choices in a `choices.py` and the whole approach would be much cleaner. 
@dhilipsiva let me know what you feel.

**Comment by rs-ds** [comment]
I am using `choices.py`. But I am using the [`orm-choices`](https://github.com/dhilipsiva/orm-choices) package: https://github.com/reckonsys/opensteer/tree/master/opensteer/users

**Comment by rmad17** [comment]
Yea, saw it buddy. Closing issue.
